/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminPassengersRouteImport } from './routes/admin.passengers'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverDashboardRouteImport } from './routes/driver.dashboard'
import { Route as DriverLoginRouteImport } from './routes/driver.login'
import { Route as DriverRegisterRouteImport } from './routes/driver.register'
import { Route as AdminDriversDriverIdRouteImport } from './routes/admin.drivers.$driverId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPassengersRoute = AdminPassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => AdminRoute,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingsRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DriverRoute,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DriverRoute,
} as any)
const DriverRegisterRoute = DriverRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DriverRoute,
} as any)
const AdminDriversDriverIdRoute = AdminDriversDriverIdRouteImport.update({
  id: '/$driverId',
  path: '/$driverId',
  getParentRoute: () => AdminDriversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/passenger': typeof PassengerRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/passengers': typeof AdminPassengersRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/register': typeof DriverRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/admin/drivers/$driverId': typeof AdminDriversDriverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passenger': typeof PassengerRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/passengers': typeof AdminPassengersRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/register': typeof DriverRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/driver': typeof DriverIndexRoute
  '/admin/drivers/$driverId': typeof AdminDriversDriverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/passenger': typeof PassengerRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/passengers': typeof AdminPassengersRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/register': typeof DriverRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/admin/drivers/$driverId': typeof AdminDriversDriverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/driver'
    | '/passenger'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/passengers'
    | '/bookings/$id'
    | '/driver/dashboard'
    | '/driver/login'
    | '/driver/register'
    | '/admin/'
    | '/bookings/'
    | '/driver/'
    | '/admin/drivers/$driverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/passenger'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/passengers'
    | '/bookings/$id'
    | '/driver/dashboard'
    | '/driver/login'
    | '/driver/register'
    | '/admin'
    | '/bookings'
    | '/driver'
    | '/admin/drivers/$driverId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/driver'
    | '/passenger'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/passengers'
    | '/bookings/$id'
    | '/driver/dashboard'
    | '/driver/login'
    | '/driver/register'
    | '/admin/'
    | '/bookings/'
    | '/driver/'
    | '/admin/drivers/$driverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  PassengerRoute: typeof PassengerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/passengers': {
      id: '/admin/passengers'
      path: '/passengers'
      fullPath: '/admin/passengers'
      preLoaderRoute: typeof AdminPassengersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/register': {
      id: '/driver/register'
      path: '/register'
      fullPath: '/driver/register'
      preLoaderRoute: typeof DriverRegisterRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/drivers/$driverId': {
      id: '/admin/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/admin/drivers/$driverId'
      preLoaderRoute: typeof AdminDriversDriverIdRouteImport
      parentRoute: typeof AdminDriversRoute
    }
  }
}

interface AdminDriversRouteChildren {
  AdminDriversDriverIdRoute: typeof AdminDriversDriverIdRoute
}

const AdminDriversRouteChildren: AdminDriversRouteChildren = {
  AdminDriversDriverIdRoute: AdminDriversDriverIdRoute,
}

const AdminDriversRouteWithChildren = AdminDriversRoute._addFileChildren(
  AdminDriversRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDriversRoute: typeof AdminDriversRouteWithChildren
  AdminPassengersRoute: typeof AdminPassengersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDriversRoute: AdminDriversRouteWithChildren,
  AdminPassengersRoute: AdminPassengersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BookingsRouteChildren {
  BookingsIdRoute: typeof BookingsIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsIdRoute: BookingsIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface DriverRouteChildren {
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverRegisterRoute: typeof DriverRegisterRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDashboardRoute: DriverDashboardRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverRegisterRoute: DriverRegisterRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  PassengerRoute: PassengerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
